#!/bin/bash
set -euo pipefail

install_rcon_cli(){

  create_temp_directory(){
    log "[LOG] CRÉATION DU RÉPERTOIRE TEMPORAIRE POUR L'INSTALLATION DE RCON CLI..."
    if RCON_TEMP_PATH=$(sudo -u "$USER_ACCOUNT" mktemp -d -t rcon_cli_install_XXXXX); then
      log "[SUCCESS] LE RÉPERTOIRE TEMPORAIRE POUR L'INSTALLATION DE RCON CLI A ÉTÉ CRÉÉ AVEC SUCCÈS."
    else
      log "[ERROR] UNE ERREUR S'EST PRODUITE LORS DE LA CRÉATION DU RÉPERTOIRE TEMPORAIRE POUR L'INSTALLATION DE RCON CLI."
      log "[DEBUG] VEUILLEZ ESSAYER DE CRÉER LE RÉPERTOIRE TEMPORAIRE MANUELLEMENT AVEC LA COMMANDE: mkdir -p $RCON_TEMP_PATH"
      exit 1
    fi
  }

  move_to_temp_directory(){
    if cd "$RCON_TEMP_PATH"; then
      log "[SUCCESS] VOUS ÊTES DANS LE RÉPERTOIRE TEMPORAIRE POUR L'INSTALLATION DE RCON CLI."
    else
      log "[ERROR] UNE ERREUR S'EST PRODUITE LORS DU DÉPLACEMENT DANS LE RÉPERTOIRE TEMPORAIRE POUR L'INSTALLATION DE RCON CLI."
      log "[DEBUG] VEUILLEZ ESSAYER DE VOUS DÉPLACER MANUELLEMENT DANS LE RÉPERTOIRE AVEC LA COMMANDE SUIVANTE:"
      log "[DEBUG] cd $RCON_TEMP_PATH"
      exit 1
    fi
  }

  download_rcon_cli(){
    log "[LOG] TÉLÉCHARGEMENT DE L'ARCHIVE RCON CLI À PARTIR DE $RCON_URL..."
    if curl -# -L "$RCON_URL" -o "$RCON_TGZ"; then
      log "[SUCCESS] ARCHIVE RCON CLI TÉLÉCHARGÉE AVEC SUCCÈS À PARTIR DE $RCON_URL."
    else
      log "[ERROR] UNE ERREUR S'EST PRODUITE LORS DU TÉLÉCHARGEMENT DE L'ARCHIVE RCON CLI À PARTIR DE $RCON_URL."
      log "[DEBUG] VEUILLEZ ESSAYER DE TÉLÉCHARGER L'ARCHIVE MANUELLEMENT AVEC LA COMMANDE: curl -# -L $RCON_URL -o $RCON_TGZ"
      exit 1
    fi
  }

  verify_rcon_cli_integrity(){
    log "[LOG] VÉRIFICATION DE L'INTÉGRITÉ DE L'ARCHIVE RCON CLI..."
    checksum=$(md5sum "$RCON_TGZ" | awk '{ print $1 }')
    if [ "$checksum" == "$RCON_CHECKSUM" ]; then
      log "[SUCCESS] L'INTÉGRITÉ DE L'ARCHIVE RCON CLI EST VÉRIFIÉE. Checksum: $checksum"
    else
      log "[ERROR] UNE ERREUR S'EST PRODUITE LORS DE LA VÉRIFICATION DE L'INTÉGRITÉ DE L'ARCHIVE RCON CLI. Checksum attendu: $RCON_CHECKSUM / Checksum actuel: $checksum"
      log "[DEBUG] VEUILLEZ VÉRIFIER L'INTÉGRITÉ DE L'ARCHIVE MANUELLEMENT AVEC LA COMMANDE: md5sum $RCON_TGZ"
      exit 1
    fi
  }

  create_rcon_directory(){
    log "[LOG] CRÉATION DU RÉPERTOIRE D'INSTALLATION DE RCON CLI POUR L'UTILISATEUR $USER_ACCOUNT..."
    if sudo -u "$USER_ACCOUNT" mkdir -p "$RCON_PATH"; then
      log "[SUCCESS] RÉPERTOIRE D'INSTALLATION DE RCON CLI CRÉÉ AVEC SUCCÈS POUR L'UTILISATEUR $USER_ACCOUNT."
    else
      log "[ERROR] UNE ERREUR S'EST PRODUITE LORS DE LA CRÉATION DU RÉPERTOIRE D'INSTALLATION DE RCON CLI."
      log "[DEBUG] VEUILLEZ ESSAYER DE CRÉER LE RÉPERTOIRE D'INSTALLATION MANUELLEMENT AVEC LA COMMANDE: sudo -u $USER_ACCOUNT mkdir -p $RCON_PATH"
      exit 1
    fi
  }

  extract_rcon_cli(){
    log "[LOG] EXTRACTION DE L'ARCHIVE RCON CLI DANS LE RÉPERTOIRE D'INSTALLATION DE L'UTILISATEUR $USER_ACCOUNT..."
    if tar -xzf "$RCON_TGZ" -C "$RCON_PATH" --strip-components=1; then
      log "[SUCCESS] ARCHIVE RCON CLI EXTRAITE AVEC SUCCÈS."
      ls "$RCON_PATH"
    else
      log "[ERROR] UNE ERREUR S'EST PRODUITE LORS DE L'EXTRACTION DE L'ARCHIVE RCON CLI DANS LE RÉPERTOIRE D'INSTALLATION."
      log "[DEBUG] VEUILLEZ ESSAYER D'EXTRAIRE L'ARCHIVE MANUELLEMENT AVEC LA COMMANDE: tar -xzf $RCON_TGZ -C $RCON_PATH --strip-components=1"
      exit 1
    fi
  }

  remove_temp_directory(){
    log "[LOG] SUPPRESSION DU RÉPERTOIRE TEMPORAIRE D'INSTALLATION DE RCON CLI..."
    if rm -rf "$RCON_TEMP_PATH"; then
      log "[SUCCESS] RÉPERTOIRE TEMPORAIRE D'INSTALLATION DE RCON CLI SUPPRIMÉ AVEC SUCCÈS."
    else
      log "[ERROR] UNE ERREUR S'EST PRODUITE LORS DE LA SUPPRESSION DU RÉPERTOIRE TEMPORAIRE D'INSTALLATION DE RCON CLI."
      log "[DEBUG] VEUILLEZ ESSAYER DE SUPPRIMER LE RÉPERTOIRE TEMPORAIRE MANUELLEMENT AVEC LA COMMANDE: rm -rf $RCON_TEMP_PATH"
      exit 1
    fi
  }

  rcon_permissions(){
    log "[LOG] VÉRIFICATION & CONFIGURATION DES PERMISSIONS D'EXÉCUTION POUR LE BINAIRE RCON CLI..."
    if [[ -x "$RCON_EXECUTABLE_PATH" ]]; then
      log "[OK] LES PERMISSIONS D'EXÉCUTION SONT DÉJÀ DÉFINIES POUR LE BINAIRE RCON CLI."
    else
      log "[WARNING] LES PERMISSIONS D'EXÉCUTION NE SONT PAS DÉFINIES POUR LE BINAIRE RCON CLI, CONFIGURATION EN COURS..."
      if sudo -u "$USER_ACCOUNT" chmod +x "$RCON_EXECUTABLE_PATH"; then
        log "[SUCCESS] LES PERMISSIONS D'EXÉCUTION ONT ÉTÉ DÉFINIES POUR LE BINAIRE RCON CLI."
      else
        log "[ERROR] UNE ERREUR S'EST PRODUITE LORS DE LA CONFIGURATION DES PERMISSIONS D'EXÉCUTION POUR LE BINAIRE RCON CLI."
        log "[DEBUG] VEUILLEZ ESSAYER DE CONFIGURER LES PERMISSIONS D'EXÉCUTION MANUELLEMENT AVEC LA COMMANDE SUIVANTE:"
        log "[DEBUG] sudo -u $USER_ACCOUNT chmod +x $RCON_EXECUTABLE_PATH"
        exit 1
      fi
    fi
  }

  log "[LOG] VÉRIFICATION & INSTALLATION DE RCON CLI SUR LE SERVEUR: $SERVER_SERVICE_NAME EN COURS..."
  if [[ -f "$RCON_EXECUTABLE_PATH" ]] && [[ -x "$RCON_EXECUTABLE_PATH" ]]; then
    log "[OK] RCON CLI EST DÉJÀ INSTALLÉ DANS LE RÉPERTOIRE $RCON_PATH POUR L'UTILISATEUR $USER_ACCOUNT."
    ls -l "$RCON_EXECUTABLE_PATH"
  else
    log "[WARNING] RCON CLI N'EST PAS INSTALLÉ, SUR LE SERVEUR: $SERVER_SERVICE_NAME, INSTALLATION EN COURS."
    create_temp_directory
    move_to_temp_directory
    download_rcon_cli
    verify_rcon_cli_integrity
    create_rcon_directory
    extract_rcon_cli
    remove_temp_directory
    rcon_permissions
    log "[SUCCESS] RCON CLI EST CORRECTEMENT INSTALLÉ DANS LE RÉPERTOIRE $RCON_PATH POUR L'UTILISATEUR $USER_ACCOUNT."
    ls -l "$RCON_EXECUTABLE_PATH"
  fi

}
