#!/bin/bash
set -euo pipefail

# Install Proton GE
install_proton_ge(){

  local PROTON_GE_TGZ
  PROTON_GE_TGZ="$(curl -s "$PROTON_GE_URL" | grep browser_download_url | cut -d\" -f4 | grep .tar.gz)"
  local PROTON_GE_VERSION
  PROTON_GE_VERSION="$(basename "$PROTON_GE_TGZ" .tar.gz)"
  local PROTON_GE_CHECKSUM
  PROTON_GE_CHECKSUM="$(curl -s "$PROTON_GE_URL" | grep browser_download_url | cut -d\" -f4 | grep .sha512sum)"
  local PROTON_GE_SHA
  PROTON_GE_SHA="$(basename "$PROTON_GE_CHECKSUM")"

  log "[LOG] VÉRIFICATION & INSTALLATION DE PROTON GE $PROTON_GE_VERSION POUR LE SERVEUR ARK: SURVIVAL ASCENDED..."

  if ! [[ -f "$PROTON_GE_EXECUTABLE_PATH" ]] && ! [[ -d "$STEAM_COMPAT_DATA_PATH/default_pfx" ]]; then
    log "[WARNING] PROTON GE N'EST PAS INSTALLÉ, INSTALLATION EN COURS..."
    log "[LOG] CRÉATION DU RÉPERTOIRE TEMPORAIRE POUR L'INSTALLATION DE $PROTON_GE_VERSION..."

    if PROTON_GE_TEMP_DIR=$(sudo -u "$USER_ACCOUNT" mktemp -d -t proton_ge_install_"${PROTON_GE_VERSION}"_XXXXX); then
      log "[SUCCESS] RÉPERTOIRE TEMPORAIRE POUR L'INSTALLATION DE $PROTON_GE_VERSION CRÉÉ AVEC SUCCÈS."
    else
      log "[ERROR] UNE ERREUR S'EST PRODUITE LORS DE LA CRÉATION DU RÉPERTOIRE TEMPORAIRE."
      log "[DEBUG] VEUILLEZ ESSAYER DE CRÉER LE RÉPERTOIRE TEMPORAIRE MANUELLEMENT AVEC LA COMMANDE: mktemp -d -t proton_ge_install_$PROTON_GE_VERSION_XXXXX"
      exit 1
    fi

    log "[LOG] DÉPLACEMENT DANS LE RÉPERTOIRE TEMPORAIRE POUR L'INSTALLATION DE $PROTON_GE_VERSION..."
    if cd "$PROTON_GE_TEMP_DIR"; then
      log "[SUCCESS] DÉPLACEMENT DANS LE RÉPERTOIRE TEMPORAIRE RÉUSSI."
    else
      log "[ERROR] UNE ERREUR S'EST PRODUITE LORS DU DÉPLACEMENT DANS LE RÉPERTOIRE TEMPORAIRE."
      log "[DEBUG] VEUILLEZ ESSAYER DE VOUS DÉPLACER MANUELLEMENT DANS LE RÉPERTOIRE TEMPORAIRE AVEC LA COMMANDE: cd $PROTON_GE_TEMP_PATH"
      exit 1
    fi

    log "[LOG] TÉLÉCHARGEMENT DE L'ARCHIVE PROTON $PROTON_GE_VERSION VERS LE RÉPERTOIRE TEMPORAIRE..."
    if sudo curl -# -L "$PROTON_GE_TGZ" -o "$PROTON_GE_VERSION.tar.gz"; then
      log "[SUCCESS] ARCHIVE PROTON $PROTON_GE_VERSION TÉLÉCHARGÉE AVEC SUCCÈS."
    else
      log "[ERROR] UNE ERREUR S'EST PRODUITE LORS DU TÉLÉCHARGEMENT DE L'ARCHIVE PROTON $PROTON_GE_VERSION."
      log "[DEBUG] VEUILLEZ ESSAYER DE TÉLÉCHARGER L'ARCHIVE MANUELLEMENT AVEC LA COMMANDE: curl -# -L $PROTON_GE_TGZ -o $PROTON_GE_VERSION.tar.gz"
      exit 1
    fi

    log "[LOG] TÉLÉCHARGEMENT DE LA SOMME DE CONTRÔLE SHA512 DE L'ARCHIVE PROTON $PROTON_GE_VERSION..."
    if sudo curl -# -L "$PROTON_GE_CHECKSUM" -o "$PROTON_GE_SHA"; then
      log "[SUCCESS] SOMME DE CONTRÔLE SHA512 DE L'ARCHIVE PROTON $PROTON_GE_VERSION TÉLÉCHARGÉE AVEC SUCCÈS."
    else
      log "[ERROR] UNE ERREUR S'EST PRODUITE LORS DU TÉLÉCHARGEMENT DE LA SOMME DE CONTRÔLE SHA512 DE L'ARCHIVE PROTON $PROTON_GE_VERSION."
      log "[DEBUG] VEUILLEZ ESSAYER DE TÉLÉCHARGER LA SOMME DE CONTRÔLE SHA512 MANUELLEMENT AVEC LA COMMANDE: curl -# -L $PROTON_GE_CHECKSUM -o $PROTON_GE_SHA"
      exit 1
    fi

    log "[LOG] VÉRIFICATION DE L'INTÉGRITÉ DE L'ARCHIVE PROTON $PROTON_GE_VERSION AVEC LA SOMME DE CONTRÔLE SHA512..."
    if sudo sha512sum -c "$PROTON_GE_SHA"; then
      log "[SUCCESS] L'INTÉGRITÉ DE L'ARCHIVE PROTON $PROTON_GE_VERSION EST VÉRIFIÉE AVEC SUCCÈS."
    else
      log "[ERROR] UNE ERREUR S'EST PRODUITE LORS DE LA VÉRIFICATION DE L'INTÉGRITÉ DE L'ARCHIVE PROTON $PROTON_GE_VERSION."
      log "[DEBUG] VEUILLEZ VÉRIFIER L'INTÉGRITÉ DE L'ARCHIVE MANUELLEMENT AVEC LA COMMANDE: sha512sum -c $PROTON_GE_SHA"
      exit 1
    fi

    log "[LOG] CRÉATION DU RÉPERTOIRE COMPATIBILITYTOOLS.D POUR L'INSTALLATION DE PROTON $PROTON_GE_VERSION..."
    if sudo -u "$USER_ACCOUNT" sudo mkdir -p "$PROTON_GE_PATH"; then
      log "[SUCCESS] RÉPERTOIRE COMPATIBILITYTOOLS.D CRÉÉ AVEC SUCCÈS POUR L'INSTALLATION DE PROTON $PROTON_GE_VERSION."
    else
      log "[ERROR] UNE ERREUR S'EST PRODUITE LORS DE LA CRÉATION DU RÉPERTOIRE COMPATIBILITYTOOLS.D."
      log "[DEBUG] VEUILLEZ ESSAYER DE CRÉER LE RÉPERTOIRE MANUELLEMENT AVEC LA COMMANDE: sudo -u $USER_ACCOUNT mkdir -p $PROTON_GE_PATH"
      exit 1
    fi

    log "[LOG] EXTRACTION DE L'ARCHIVE PROTON $PROTON_GE_VERSION DANS LE RÉPERTOIRE COMPATIBILITYTOOLS.D..."
    if tar -xzf "$PROTON_GE_VERSION.tar.gz" -C "$PROTON_GE_PATH" --strip-components=1; then
      log "[SUCCESS] ARCHIVE PROTON $PROTON_GE_VERSION EXTRAITE AVEC SUCCÈS."
      ls "$PROTON_GE_PATH"
    else
      log "[ERROR] UNE ERREUR S'EST PRODUITE LORS DE L'EXTRACTION DE L'ARCHIVE PROTON $PROTON_GE_VERSION."
      log "[DEBUG] VEUILLEZ ESSAYER D'EXTRAIRE L'ARCHIVE MANUELLEMENT AVEC LA COMMANDE: tar -xzf $PROTON_GE_VERSION.tar.gz -C $PROTON_GE_PATH"
      exit 1
    fi

    log "[LOG] SUPPRESSION DU RÉPERTOIRE TEMPORAIRE POUR L'INSTALLATION DE PROTON $PROTON_GE_VERSION..."
    if rm -rf "$PROTON_GE_TEMP_DIR"; then
      log "[SUCCESS] RÉPERTOIRE TEMPORAIRE SUPPRIMÉ AVEC SUCCÈS APRÈS L'INSTALLATION DE PROTON $PROTON_GE_VERSION."
    else
      log "[ERROR] UNE ERREUR S'EST PRODUITE LORS DE LA SUPPRESSION DU RÉPERTOIRE TEMPORAIRE."
      log "[DEBUG] VEUILLEZ ESSAYER DE SUPPRIMER LE RÉPERTOIRE TEMPORAIRE MANUELLEMENT AVEC LA COMMANDE: rm -rf $PROTON_GE_TEMP_PATH"
      exit 1
    fi

    log "[LOG] CRÉATION DU RÉPERTOIRE COMPATDATA POUR LE SERVEUR ARK: SURVIVAL ASCENDED ET PROTON $PROTON_GE_VERSION..."
    if sudo -u "$USER_ACCOUNT" mkdir -p "$STEAM_COMPAT_DATA_PATH"; then
      log "[SUCCESS] RÉPERTOIRE COMPATDATA CRÉÉ AVEC SUCCÈS POUR LE SERVEUR ARK: SURVIVAL ASCENDED."
    else
      log "[ERROR] UNE ERREUR S'EST PRODUITE LORS DE LA CRÉATION DU RÉPERTOIRE COMPATDATA POUR LE SERVEUR ARK: SURVIVAL ASCENDED."
      log "[DEBUG] VEUILLEZ ESSAYER DE CRÉER LE RÉPERTOIRE MANUELLEMENT AVEC LA COMMANDE: sudo -u $USER_ACCOUNT mkdir -p $STEAM_COMPAT_DATA_PATH"
      exit 1
    fi

    log "[LOG] COPIE DES FICHIERS DE COMPATIBILITÉ PROTON $PROTON_GE_VERSION DANS LE RÉPERTOIRE COMPATDATA DU SERVEUR ARK: SURVIVAL ASCENDED..."
    if sudo -u "$USER_ACCOUNT" cp -r "$PROTON_GE_PATH/files/share/default_pfx" "$STEAM_COMPAT_DATA_PATH"; then
      log "[SUCCESS] LES FICHIERS DE COMPATIBILITÉ PROTON $PROTON_GE_VERSION ONT ÉTÉ COPIÉS AVEC SUCCÈS DANS LE RÉPERTOIRE COMPATDATA DU SERVEUR ARK: SURVIVAL ASCENDED."
      ls -l "$STEAM_COMPAT_DATA_PATH"
    else
      log "[ERROR] UNE ERREUR S'EST PRODUITE LORS DE LA COPIE DES FICHIERS DE COMPATIBILITÉ PROTON $PROTON_GE_VERSION."
      log "[DEBUG] VEUILLEZ ESSAYER DE COPIER LES FICHIERS MANUELLEMENT AVEC LA COMMANDE: sudo -u $USER_ACCOUNT cp -r $PROTON_GE_PATH/files/share/default_pfx $STEAM_COMPAT_DATA_PATH"
      exit 1
    fi

  else
    log "[OK] PROTON $PROTON_GE_VERSION EST CORRECTEMENT INSTALLÉ & CONFIGURÉ POUR LE SERVEUR ARK: SURVIVAL ASCENDED."
    ls -l "$PROTON_GE_PATH"
    ls -l "$STEAM_COMPAT_DATA_PATH"
  fi

}
