#!/bin/bash
set -euo pipefail

install_server(){

  log "[LOG] VÉRIFICATION & INSTALLATION DU SERVEUR: $SERVER_SERVICE_NAME SUR $HOSTNAME..."
  if [[ -x "$ARK_SERVER_EXECUTABLE_PATH" ]]; then
    log "[OK] LE SERVEUR: $SERVER_SERVICE_NAME EST DÉJÀ INSTALLÉ DANS $ARK_SERVER_PATH SUR $HOSTNAME."
    ls -l "$ARK_SERVER_PATH"
  else
    log "[WARNING] LE SERVEUR: $SERVER_SERVICE_NAME N'EST PAS ENCORE INSTALLÉ DANS $ARK_SERVER_PATH SUR $HOSTNAME, INSTALLATION EN COURS."
    log "[LOG] TÉLÉCHARGEMENT DU SERVEUR: $SERVER_SERVICE_NAME EN COURS."
    if sudo -u "$USER_ACCOUNT" "$STEAM_CMD_PATH" +force_install_dir "$ARK_SERVER_PATH" +login anonymous +app_update "$ARK_APP_ID" validate +quit; then
      log "[SUCCESS] LE SERVEUR: $SERVER_SERVICE_NAME A ÉTÉ INSTALLÉ AVEC SUCCÈS DANS $ARK_SERVER_PATH SUR $HOSTNAME."
      ls -l "$ARK_SERVER_PATH"
    else
      log "[ERROR] UNE ERREUR S'EST PRODUITE LORS DE L'INSTALLATION DU SERVEUR: $SERVER_SERVICE_NAME DANS $ARK_SERVER_PATH SUR $HOSTNAME."
      log "[DEBUG] VEUILLEZ ESSAYER D'INSTALLER LE SERVEUR: $SERVER_SERVICE_NAME MANUELLEMENT AVEC LA COMMANDE SUIVANTE:"
      log "[DEBUG] sudo -u $USER_ACCOUNT $STEAM_CMD_PATH +force_install_dir $ARK_SERVER_PATH +login anonymous +app_update $ARK_APP_ID validate +quit"
      exit 1
    fi
  fi

}