#!/bin/bash
set -euo pipefail

server_management_create() {

  copy_manager_folder(){
    log "[LOG] VÉRIFICATION & COPIE DU RÉPERTOIRE DE MANAGEMENT DU SERVEUR $SERVER_SERVICE_NAME POUR L'UTILISATEUR $USER_ACCOUNT..."
    if [[ -d "/home/$USER_ACCOUNT/manager" ]]; then
      log "[OK] LE RÉPERTOIRE DE MANAGEMENT DU SERVEUR $SERVER_SERVICE_NAME EXISTE DÉJÀ POUR L'UTILISATEUR $USER_ACCOUNT"
      ls -la "/home/$USER_ACCOUNT/manager"
    else
      log "[WARNING] LE RÉPERTOIRE DE MANAGEMENT DU SERVEUR $SERVER_SERVICE_NAME N'EXISTE PAS POUR L'UTILISATEUR $USER_ACCOUNT, CRÉATION EN COURS..."
      log "[LOG] COPIE DU RÉPERTOIRE MANAGER ET SON CONTENU POUR L'UTILISATEUR $USER_ACCOUNT..."
      if cp -r "$SCRIPTS_DIR/manager" "/home/$USER_ACCOUNT"; then
        log "[SUCCESS] LE RÉPERTOIRE MANAGER ET SON CONTENU ONT ÉTÉ COPIÉS AVEC SUCCÈS POUR L'UTILISATEUR $USER_ACCOUNT."
        ls -la "/home/$USER_ACCOUNT/manager"
      else
        log "[ERROR] UNE ERREUR S'EST PRODUITE LORS DE LA COPIE DU RÉPERTOIRE MANAGER ET SON CONTENU POUR L'UTILISATEUR $USER_ACCOUNT."
        log "[DEBUG] VEUILLEZ COPIER LE RÉPERTOIRE MANAGER ET SON CONTENU POUR L'UTILISATEUR $USER_ACCOUNT À L'AIDE DE LA COMMANDE SUIVANTE:"
        log "[DEBUG] sudo cp -r $SCRIPTS_DIR/manager /home/$USER_ACCOUNT"
        exit 1
      fi
    fi
  }

  copy_config_files(){
    log "[LOG] VÉRIFICATION & COPIE DES FICHIERS DE CONFIGURATION DU SCRIPT DE MANAGEMENT POUR L'UTILISATEUR $USER_ACCOUNT..."
    if [[ -d "/home/$USER_ACCOUNT/manager/config" ]]; then
      log "[OK] LE RÉPERTOIRE DE CONFIGURATION DU SCRIPT DE MANAGEMENT EXISTE DÉJÀ POUR L'UTILISATEUR $USER_ACCOUNT"
      ls -la "/home/$USER_ACCOUNT/manager/config"
    else
      log "[WARNING] LE RÉPERTOIRE DE CONFIGURATION DU SCRIPT DE MANAGEMENT N'EXISTE PAS POUR L'UTILISATEUR $USER_ACCOUNT, COPIE EN COURS..."
      log "[LOG] COPIE DES FICHIERS DE CONFIGURATION COMMUN & SERVEUR DU SCRIPT DE MANAGEMENT POUR L'UTILISATEUR $USER_ACCOUNT..."
      if cp -r "$CONFIG_DIR/common.sh" "$CONFIG_DIR/server.sh" "/home/$USER_ACCOUNT/manager/config"; then
        log "[SUCCESS] LES FICHIERS DE CONFIGURATION COMMUN & SERVEUR DU SCRIPT DE MANAGEMENT ONT ÉTÉ COPIÉS AVEC SUCCÈS POUR L'UTILISATEUR $USER_ACCOUNT."
        ls -la "/home/$USER_ACCOUNT/manager/config"
      else
        log "[ERROR] UNE ERREUR S'EST PRODUITE LORS DE LA COPIE DES FICHIERS DE CONFIGURATION DU SCRIPT DE MANAGEMENT POUR L'UTILISATEUR $USER_ACCOUNT."
        log "[DEBUG] VEUILLEZ COPIER LES FICHIERS DE CONFIGURATION DU SCRIPT DE MANAGEMENT POUR L'UTILISATEUR $USER_ACCOUNT À L'AIDE DE LA COMMANDE SUIVANTE:"
        log "[DEBUG] sudo -u $USER_ACCOUNT cp $CONFIG_DIR/common.sh $CONFIG_DIR/server.sh /home/$USER_ACCOUNT/manager/config"
        exit 1
      fi
    fi
  }

  copy_custom_files(){
    log "[LOG] VÉRIFICATION & COPIE DES FICHIERS CUSTOM DU SCRIPT DE MANAGEMENT POUR L'UTILISATEUR $USER_ACCOUNT..."
    if [[ -d "/home/$USER_ACCOUNT/manager/custom" ]]; then
      log "[OK] LE RÉPERTOIRE CUSTOM DU SCRIPT DE MANAGEMENT EXISTE DÉJÀ POUR L'UTILISATEUR $USER_ACCOUNT"
      ls -la "/home/$USER_ACCOUNT/manager/custom"
    else
      log "[WARNING] LE RÉPERTOIRE CUSTOM DU SCRIPT DE MANAGEMENT N'EXISTE PAS POUR L'UTILISATEUR $USER_ACCOUNT, COPIE EN COURS..."
      log "[LOG] COPIE DES FICHIERS DE DÉPENDANCES DU SCRIPT DE MANAGEMENT POUR L'UTILISATEUR $USER_ACCOUNT..."
      if cp -r "$SCRIPTS_DIR/custom/custom_shell_logs.sh" "/home/$USER_ACCOUNT/manager/custom"; then
        log "[SUCCESS] LES FICHIERS DE DÉPENDANCES DU SCRIPT DE MANAGEMENT ONT ÉTÉ COPIÉS AVEC SUCCÈS POUR L'UTILISATEUR $USER_ACCOUNT."
        ls -la "/home/$USER_ACCOUNT/manager/custom"
      else
        log "[ERROR] UNE ERREUR S'EST PRODUITE LORS DE LA COPIE DES FICHIERS DE DÉPENDANCES DU SCRIPT DE MANAGEMENT POUR L'UTILISATEUR $USER_ACCOUNT."
        log "[DEBUG] VEUILLEZ COPIER LES FICHIERS DE DÉPENDANCES DU SCRIPT DE MANAGEMENT POUR L'UTILISATEUR $USER_ACCOUNT À L'AIDE DE LA COMMANDE SUIVANTE:"
        log "[DEBUG] sudo -u $USER_ACCOUNT cp $SCRIPTS_DIR/custom/custom_shell_logs.sh /home/$USER_ACCOUNT/manager/custom"
        exit 1
      fi
    fi
  }

  copy_tools_files(){
    log "[LOG] VÉRIFICATION & COPIE DES FICHIERS TOOLS DU SCRIPT DE MANAGEMENT POUR L'UTILISATEUR $USER_ACCOUNT..."
    if [[ -d "/home/$USER_ACCOUNT/manager/tools" ]]; then
      log "[OK] LE RÉPERTOIRE TOOLS DU SCRIPT DE MANAGEMENT EXISTE DÉJÀ POUR L'UTILISATEUR $USER_ACCOUNT"
      ls -la "/home/$USER_ACCOUNT/manager/tools"
    else
      log "[WARNING] LE RÉPERTOIRE TOOLS DU SCRIPT DE MANAGEMENT N'EXISTE PAS POUR L'UTILISATEUR $USER_ACCOUNT, COPIE EN COURS..."
      log "[LOG] COPIE DES FICHIERS TOOLS DU SCRIPT DE MANAGEMENT POUR L'UTILISATEUR $USER_ACCOUNT..."
      if cp -r "$SCRIPTS_DIR/tools/format_text.sh" "$SCRIPTS_DIR/tools/check_system_update.sh" "/home/$USER_ACCOUNT/manager/tools"; then
        log "[SUCCESS] LES FICHIERS TOOLS DU SCRIPT DE MANAGEMENT ONT ÉTÉ COPIÉS AVEC SUCCÈS POUR L'UTILISATEUR $USER_ACCOUNT."
        ls -la "/home/$USER_ACCOUNT/manager/tools"
      else
        log "[ERROR] UNE ERREUR S'EST PRODUITE LORS DE LA COPIE DES FICHIERS TOOLS DU SCRIPT DE MANAGEMENT POUR L'UTILISATEUR $USER_ACCOUNT."
        log "[DEBUG] VEUILLEZ COPIER LES FICHIERS TOOLS DU SCRIPT DE MANAGEMENT POUR L'UTILISATEUR $USER_ACCOUNT À L'AIDE DE LA COMMANDE SUIVANTE:"
        log "[DEBUG] sudo -u $USER_ACCOUNT cp -r $SCRIPTS_DIR/tools/format_text.sh $SCRIPTS_DIR/tools/check_system_update.sh /home/$USER_ACCOUNT/manager/tools"
        exit 1
      fi
    fi
  }

  check_permission_manager(){
    log "[LOG] VÉRIFICATION & AJOUT DES PERMISSIONS AU RÉPERTOIRE DE MANAGEMENT POUR L'UTILISATEUR $USER_ACCOUNT..."
    if sudo chown -R "$USER_ACCOUNT":"$USER_ACCOUNT" "/home/$USER_ACCOUNT/manager"; then
      log "[OK] LES PERMISSIONS DU RÉPERTOIRE DE MANAGEMENT SONT DÉJÀ CORRECTES POUR L'UTILISATEUR $USER_ACCOUNT."
    else
      log "[WARNING] LES PERMISSIONS DU RÉPERTOIRE DE MANAGEMENT NE SONT PAS CORRECTES POUR L'UTILISATEUR $USER_ACCOUNT, AJOUT EN COURS..."
      log "[LOG] AJOUT DES PERMISSIONS AU RÉPERTOIRE DE MANAGEMENT POUR L'UTILISATEUR $USER_ACCOUNT..."
      if sudo chown -R "$USER_ACCOUNT":"$USER_ACCOUNT" "/home/$USER_ACCOUNT/manager"; then
        log "[SUCCESS] LES PERMISSIONS ONT ÉTÉ AJOUTÉES AVEC SUCCÈS AU RÉPERTOIRE DE MANAGEMENT POUR L'UTILISATEUR $USER_ACCOUNT."
      else
        log "[ERROR] UNE ERREUR S'EST PRODUITE LORS DE L'AJOUT DES PERMISSIONS AU RÉPERTOIRE DE MANAGEMENT POUR L'UTILISATEUR $USER_ACCOUNT."
        log "[DEBUG] VEUILLEZ AJOUTER LES PERMISSIONS AU RÉPERTOIRE DE MANAGEMENT POUR L'UTILISATEUR $USER_ACCOUNT À L'AIDE DE LA COMMANDE SUIVANTE:"
        log "[DEBUG] sudo chown -R $USER_ACCOUNT:$USER_ACCOUNT /home/$USER_ACCOUNT/manager"
        exit 1
      fi
    fi

    log "[LOG] VÉRIFICATION & ACTIVATION DES PERMISSIONS D'EXÉCUTION DU SCRIPT DE MANAGEMENT POUR L'UTILISATEUR $USER_ACCOUNT..."
    if [[ -x "$MANAGEMENT_SCRIPT_PATH" ]]; then
      log "[OK] LE SCRIPT DE MANAGEMENT EST DÉJÀ EXÉCUTABLE POUR L'UTILISATEUR $USER_ACCOUNT."
    else
      log "[WARNING] LE SCRIPT DE MANAGEMENT N'EST PAS EXÉCUTABLE POUR L'UTILISATEUR $USER_ACCOUNT, ACTIVATION EN COURS..."
      log "[LOG] ACTIVATION DES PERMISSIONS D'EXÉCUTION DU SCRIPT DE MANAGEMENT POUR L'UTILISATEUR $USER_ACCOUNT..."
      if sudo -u "$USER_ACCOUNT" chmod +x "$MANAGEMENT_SCRIPT_PATH"; then
        log "[SUCCESS] LE SCRIPT DE MANAGEMENT A ÉTÉ RENDU EXÉCUTABLE AVEC SUCCÈS POUR L'UTILISATEUR $USER_ACCOUNT."
        ls -la "$MANAGEMENT_SCRIPT_PATH"
      else
        log "[ERROR] UNE ERREUR S'EST PRODUITE LORS DU RENDU EXÉCUTABLE DU SCRIPT DE MANAGEMENT POUR L'UTILISATEUR $USER_ACCOUNT."
        log "[DEBUG] VEUILLEZ RENDRE EXÉCUTABLE LE SCRIPT DE MANAGEMENT POUR L'UTILISATEUR $USER_ACCOUNT À L'AIDE DE LA COMMANDE SUIVANTE:"
        log "[DEBUG] sudo -u $USER_ACCOUNT chmod +x $MANAGEMENT_SCRIPT_PATH"
        exit 1
      fi
    fi
  }

  check_bashrc_file(){
    log "[LOG] VÉRIFICATION & MODIFICATION DU FICHIER .bashrc DE L'UTILISATEUR $USER_ACCOUNT..."
    if grep -q "alias manager='$MANAGEMENT_SCRIPT_PATH'" "/home/$USER_ACCOUNT/.bashrc"; then
      log "[OK] LE RACCOURCI POUR LE SCRIPT DE MANAGEMENT EXISTE DÉJÀ DANS LE FICHIER .bashrc DE L'UTILISATEUR $USER_ACCOUNT."
    else
      log "[WARNING] LE RACCOURCI POUR LE SCRIPT DE MANAGEMENT N'EXISTE PAS DANS LE FICHIER .bashrc DE L'UTILISATEUR $USER_ACCOUNT."
      log "[LOG] AJOUT DU RACCOURCI POUR LE SCRIPT DE MANAGEMENT DANS LE FICHIER .bashrc DE L'UTILISATEUR $USER_ACCOUNT..."
      if echo "alias manager='$MANAGEMENT_SCRIPT_PATH'" >> "/home/$USER_ACCOUNT/.bashrc"; then
        log "[SUCCESS] LE RACCOURCI POUR LE SCRIPT DE MANAGEMENT A ÉTÉ AJOUTÉ AVEC SUCCÈS DANS LE FICHIER .bashrc DE L'UTILISATEUR $USER_ACCOUNT."
        log "[INFO] EXEMPLE DE COMMANDE POUR UTILISER LE SCRIPT DE MANAGEMENT: manager auto_update"
      else
        log "[ERROR] UNE ERREUR S'EST PRODUITE LORS DE L'AJOUT DU RACCOURCI POUR LE SCRIPT DE MANAGEMENT DANS LE FICHIER .bashrc DE L'UTILISATEUR $USER_ACCOUNT."
        log "[DEBUG] VEUILLEZ AJOUTER LE RACCOURCI POUR LE SCRIPT DE MANAGEMENT DANS LE FICHIER .bashrc DE L'UTILISATEUR $USER_ACCOUNT À L'AIDE DE LA COMMANDE SUIVANTE:"
        log "[DEBUG] echo 'alias manager='$MANAGEMENT_SCRIPT_PATH'' >> /home/$USER_ACCOUNT/.bashrc"
        exit 1
      fi
    fi

    log "[LOG] VÉRIFICATION & CHARGEMENT DU FICHIER .bashrc DE L'UTILISATEUR $USER_ACCOUNT..."
    # shellcheck source=/home/$USER_ACCOUNT/.bashrc
    if source "/home/$USER_ACCOUNT/.bashrc"; then
      log "[SUCCESS] LE FICHIER .bashrc DE L'UTILISATEUR $USER_ACCOUNT A ÉTÉ CHARGÉ AVEC SUCCÈS."
    else
      log "[ERROR] UNE ERREUR S'EST PRODUITE LORS DU CHARGEMENT DU FICHIER .bashrc DE L'UTILISATEUR $USER_ACCOUNT."
      log "[DEBUG] VEUILLEZ CHARGER LE FICHIER .bashrc DE L'UTILISATEUR $USER_ACCOUNT À L'AIDE DE LA COMMANDE SUIVANTE:"
      log "[DEBUG] source /home/$USER_ACCOUNT/.bashrc"
      exit 1
    fi
  }

  copy_manager_folder
  copy_config_files
  copy_custom_files
  copy_tools_files

  check_permission_manager
  check_bashrc_file

  log "[SUCCESS] LE SCRIPT DE MANAGEMENT EST CORRECTEMENT CONFIGURÉ POUR LE SERVEUR $SERVER_SERVICE_NAME."
}



