#!/bin/bash
set -euo pipefail

server_management_create() {

  log "[LOG] VÉRIFICATION & CRÉATION DES FICHIERS DE MANAGEMENT DU SERVEUR ARK: $SERVICE_NAME POUR L'UTILISATEUR $USER_ACCOUNT"

  if [[ -d "/home/$USER_ACCOUNT/manager" ]]; then
    log "[OK] LE RÉPERTOIRE DE MANAGEMENT DU SERVEUR $SERVICE_NAME EXISTE DÉJÀ POUR L'UTILISATEUR $USER_ACCOUNT"
    ls -la "/home/$USER_ACCOUNT/manager"
  else

    log "[WARNING] LE RÉPERTOIRE DE MANAGEMENT DU SERVEUR $SERVICE_NAME N'EXISTE PAS POUR L'UTILISATEUR $USER_ACCOUNT, CRÉATION EN COURS..."

    log "[LOG] COPIE DU RÉPERTOIRE MANAGER ET SON CONTENU POUR L'UTILISATEUR $USER_ACCOUNT..."
    if cp -r "$SCRIPTS_DIR/manager" "/home/$USER_ACCOUNT"; then
      log "[SUCCESS] LE RÉPERTOIRE MANAGER ET SON CONTENU ONT ÉTÉ COPIÉS AVEC SUCCÈS POUR L'UTILISATEUR $USER_ACCOUNT."
      ls -la "/home/$USER_ACCOUNT/manager"
    else
      log "[ERROR] UNE ERREUR S'EST PRODUITE LORS DE LA COPIE DU RÉPERTOIRE MANAGER ET SON CONTENU POUR L'UTILISATEUR $USER_ACCOUNT."
      log "[DEBUG] VEUILLEZ COPIER LE RÉPERTOIRE MANAGER ET SON CONTENU POUR L'UTILISATEUR $USER_ACCOUNT À L'AIDE DE LA COMMANDE SUIVANTE:"
      log "[DEBUG] sudo cp -r $SCRIPTS_DIR/manager /home/$USER_ACCOUNT"
      exit 1
    fi

    log "[LOG] COPIE DES FICHIERS DE DÉPENDANCES DU SCRIPT DE MANAGEMENT POUR L'UTILISATEUR $USER_ACCOUNT..."
    if cp "$SCRIPTS_DIR/custom/custom_shell_logs.sh" "/home/$USER_ACCOUNT/manager/custom"; then
      log "[SUCCESS] LES FICHIERS DE DÉPENDANCES DU SCRIPT DE MANAGEMENT ONT ÉTÉ COPIÉS AVEC SUCCÈS POUR L'UTILISATEUR $USER_ACCOUNT."
      ls -la "/home/$USER_ACCOUNT/manager/custom"
    else
      log "[ERROR] UNE ERREUR S'EST PRODUITE LORS DE LA COPIE DES FICHIERS DE DÉPENDANCES DU SCRIPT DE MANAGEMENT POUR L'UTILISATEUR $USER_ACCOUNT."
      log "[DEBUG] VEUILLEZ COPIER LES FICHIERS DE DÉPENDANCES DU SCRIPT DE MANAGEMENT POUR L'UTILISATEUR $USER_ACCOUNT À L'AIDE DE LA COMMANDE SUIVANTE:"
      log "[DEBUG] sudo -u $USER_ACCOUNT cp $SCRIPTS_DIR/custom/custom_shell_logs.sh /home/$USER_ACCOUNT/manager/custom"
      exit 1
    fi

    log "[LOG] COPIE DES FICHIERS DE CONFIGURATION COMMUN & SERVEUR DU SCRIPT DE MANAGEMENT POUR L'UTILISATEUR $USER_ACCOUNT..."
    if cp "$CONFIG_DIR/common.sh" "$CONFIG_DIR/server.sh" "/home/$USER_ACCOUNT/manager/config"; then
      log "[SUCCESS] LES FICHIERS DE CONFIGURATION COMMUN & SERVEUR DU SCRIPT DE MANAGEMENT ONT ÉTÉ COPIÉS AVEC SUCCÈS POUR L'UTILISATEUR $USER_ACCOUNT."
      ls -la "/home/$USER_ACCOUNT/manager/config"
    else
      log "[ERROR] UNE ERREUR S'EST PRODUITE LORS DE LA COPIE DES FICHIERS DE CONFIGURATION DU SCRIPT DE MANAGEMENT POUR L'UTILISATEUR $USER_ACCOUNT."
      log "[DEBUG] VEUILLEZ COPIER LES FICHIERS DE CONFIGURATION DU SCRIPT DE MANAGEMENT POUR L'UTILISATEUR $USER_ACCOUNT À L'AIDE DE LA COMMANDE SUIVANTE:"
      log "[DEBUG] sudo -u $USER_ACCOUNT cp $CONFIG_DIR/common.sh $CONFIG_DIR/server.sh /home/$USER_ACCOUNT/manager/config"
      exit 1
    fi

    log "[LOG] COPIE DES FICHIERS TOOLS DU SCRIPT DE MANAGEMENT POUR L'UTILISATEUR $USER_ACCOUNT..."
    if cp -r "$SCRIPTS_DIR/tools/format_text.sh" "$SCRIPTS_DIR/tools/check_system_update.sh" "/home/$USER_ACCOUNT/manager/tools"; then
      log "[SUCCESS] LES FICHIERS TOOLS DU SCRIPT DE MANAGEMENT ONT ÉTÉ COPIÉS AVEC SUCCÈS POUR L'UTILISATEUR $USER_ACCOUNT."
      ls -la "/home/$USER_ACCOUNT/manager/tools"
    else
      log "[ERROR] UNE ERREUR S'EST PRODUITE LORS DE LA COPIE DES FICHIERS TOOLS DU SCRIPT DE MANAGEMENT POUR L'UTILISATEUR $USER_ACCOUNT."
      log "[DEBUG] VEUILLEZ COPIER LES FICHIERS TOOLS DU SCRIPT DE MANAGEMENT POUR L'UTILISATEUR $USER_ACCOUNT À L'AIDE DE LA COMMANDE SUIVANTE:"
      log "[DEBUG] sudo -u $USER_ACCOUNT cp -r $SCRIPTS_DIR/tools/format_text.sh $SCRIPTS_DIR/tools/check_system_update.sh /home/$USER_ACCOUNT/manager/tools"
      exit 1
    fi

    log "[LOG] AJOUT DES PERMISSIONS AU RÉPERTOIRE DE MANAGEMENT POUR L'UTILISATEUR $USER_ACCOUNT..."
    if sudo chown -R "$USER_ACCOUNT":"$USER_ACCOUNT" "/home/$USER_ACCOUNT/manager"; then
      log "[SUCCESS] LES PERMISSIONS ONT ÉTÉ AJOUTÉES AVEC SUCCÈS AU RÉPERTOIRE DE MANAGEMENT POUR L'UTILISATEUR $USER_ACCOUNT."
    else
      log "[ERROR] UNE ERREUR S'EST PRODUITE LORS DE L'AJOUT DES PERMISSIONS AU RÉPERTOIRE DE MANAGEMENT POUR L'UTILISATEUR $USER_ACCOUNT."
      log "[DEBUG] VEUILLEZ AJOUTER LES PERMISSIONS AU RÉPERTOIRE DE MANAGEMENT POUR L'UTILISATEUR $USER_ACCOUNT À L'AIDE DE LA COMMANDE SUIVANTE:"
      log "[DEBUG] sudo chown -R $USER_ACCOUNT:$USER_ACCOUNT /home/$USER_ACCOUNT/manager"
      exit 1
    fi

    log "[LOG] ACTIVATION DES PERMISSIONS D'EXÉCUTION DU SCRIPT DE MANAGEMENT POUR L'UTILISATEUR $USER_ACCOUNT..."
    if sudo -u "$USER_ACCOUNT" chmod +x "/home/$USER_ACCOUNT/manager/manager.sh"; then
      log "[SUCCESS] LE SCRIPT DE MANAGEMENT A ÉTÉ RENDU EXÉCUTABLE AVEC SUCCÈS POUR L'UTILISATEUR $USER_ACCOUNT."
      ls -la "/home/$USER_ACCOUNT/manager/manager.sh"
    else
      log "[ERROR] UNE ERREUR S'EST PRODUITE LORS DU RENDU EXÉCUTABLE DU SCRIPT DE MANAGEMENT POUR L'UTILISATEUR $USER_ACCOUNT."
      log "[DEBUG] VEUILLEZ RENDRE EXÉCUTABLE LE SCRIPT DE MANAGEMENT POUR L'UTILISATEUR $USER_ACCOUNT À L'AIDE DE LA COMMANDE SUIVANTE:"
      log "[DEBUG] sudo -u $USER_ACCOUNT chmod +x /home/$USER_ACCOUNT/manager/manager.sh"
      exit 1
    fi

    log "[SUCCESS] LE RÉPERTOIRE DE MANAGEMENT DU SERVEUR $SERVICE_NAME A ÉTÉ CRÉÉ AVEC SUCCÈS POUR L'UTILISATEUR $USER_ACCOUNT."

  fi

}



