#!/bin/bash
set -euo pipefail

# [ System ]
USER_ACCOUNT="ark-admin"

# [ ARK: Survival Ascended Server Configuration ]
MAP_NAME="TheIsland_WP"
SERVER_NAME="PROTONARK1"
GAME_PORT="7779"
SERVER_PASSWORD=""
SERVER_ADMIN_PASSWORD="YOURADMINPASSWORDHERE"
RCON_ENABLED="True"
RCON_PORT="11640"
PREVENT_SPAWN_ANIMATION="True"
WIN_LIVE_MAX_PLAYERS="20"

# [ ARK: Survival Ascended Server Cluster Configuration ]
NAS_IP_ADDRESS="192.168.1.5"
NAS_FOLDER_PATH="/volume1/CLUSTER-PVE"
CLUSTER_FOLDER="ClusterPVE"
CLUSTER_DIR_OVERRIDE="/home/${USER_ACCOUNT}/${CLUSTER_FOLDER}"
MULTIHOME="192.168.1.105"
CLUSTER_ID="123"
PREVENT_DOWNLOAD_SURVIVORS="False"
PREVENT_DOWNLOAD_ITEMS="False"
PREVENT_DOWNLOAD_DINOS="False"
NO_TRIBUTE_DOWNLOADS="False"
NO_TRANSFER_FROM_FILTERING="Yes"