#!/bin/bash
set -euo pipefail

check_variables(){
  log "[LOG] VÉRIFICATION & VALIDATION DES VARIABLES DE CONFIGURATION POUR LE CLUSTER DYNAMIQUE..."
  if [ -z "$USE_DYNAMIC_CONFIG" ]; then
    echo "USE_DYNAMIC_CONFIG: $USE_DYNAMIC_CONFIG"
    log "[ERROR] VEUILLEZ DÉFINIR L'UTILISATION DE LA CONFIGURATION DYNAMIQUE DANS LA VARIABLE USE_DYNAMIC_CONFIG DU FICHIER DE CONFIGURATION."
    log "[INFO] EXEMPLE D'UTILISATION DE LA CONFIGURATION DYNAMIQUE: Yes"
    exit 1
  elif [ -f "$DYNAMIC_CONFIG_DIR" ]; then
    log "[ERROR] LE DOSSIER DE CONFIGURATION DYNAMIQUE N'EXISTE PAS DANS LE RÉPERTOIRE $DYNAMIC_CONFIG_DIR."
    log "[INFO] EXEMPLE DE DOSSIER DE CONFIGURATION DYNAMIQUE: /home/overseer/dynamic"
    exit 1
  fi
  log "[SUCCESS] TOUTES LES VARIABLES DE CONFIGURATION SONT DÉFINIES CORRECTEMENT."
}

create_dynamic(){

  log "[WARNING] VOULEZ VOUS UTILISER LA CONFIGURATION DYNAMIQUE POUR CE SERVEUR ARK: $SERVER_SERVICE_NAME ?"
  log "[ATTENTION] LA CONFIGURATION DYNAMIQUE PERMET DE MODIFIER LES PARAMÈTRES DE CONFIGURATION SANS REDÉMARRER LE SERVEUR."
  log "[ATTENTION] VEUILLEZ VOUS ASSURER QUE UseDynamicConfig EST DÉFINI À Yes DANS LE FICHIER DE CONFIGURATION Server.sh."
  if read -r -p "Entrez votre choix [O/o/N/n/Oui/Non]: " choice; then
    case $choice in
    [oO][uU][iI]|[oO])
      log "[LOG] CRÉATION DE LA CONFIGURATION DYNAMIQUE POUR LE SERVEUR ARK: $SERVER_SERVICE_NAME..."
      check_variables
      update_gus_ini "CustomDynamicConfigUrl" "\"${DYNAMIC_CONFIG_URL}\""
      update_command_line "add_simple_flag_params" "UseDynamicConfig" ""
      daemon_reload
      service_create "web_server"
      log "[SUCCESS] LA CONFIGURATION DYNAMIQUE A ÉTÉ CRÉÉE AVEC SUCCÈS POUR LE SERVEUR ARK: $SERVER_SERVICE_NAME."
      ;;
    [nN][oO]|[nN])
      log "[LOG] LA CONFIGURATION DYNAMIQUE NE SERA PAS UTILISÉE POUR LE SERVEUR ARK: $SERVER_SERVICE_NAME."
      exit 0
      ;;
    *)
      log "[ERROR] CHOIX INVALIDE: $choice. VEUILLEZ SAISIR [O/o/N/n/Oui/Non] POUR CONTINUER."
      create_dynamic
      ;;
    esac
  else
    log "[ERROR] ERREUR LORS DE LA SAISIE DU CHOIX POUR L'UTILISATION DE LA CONFIGURATION DYNAMIQUE."
    log "[DEBUG] VEUILLEZ SAISIR UNE RÉPONSE VALIDE: [O/o/N/n/Oui/Non]"
    log "[DEBUG] VEUILLEZ RÉESSAYER POUR L'UTILISATION DE LA CONFIGURATION DYNAMIQUE POUR LE SERVEUR ARK: $SERVER_SERVICE_NAME."
    log "[DEBUG] POUR POUR L'INSTALLATION DU CLUSTER NFS, SAISISSEZ O/o/Oui/oui POUR CONTINUER OU N/n/Non/non POUR ANNULER."
    exit 1
  fi

}
